DROP TABLE AutomaticMachine CASCADE CONSTRAINTS;
DROP TABLE BillOfMaterials CASCADE CONSTRAINTS;
DROP TABLE BillOfOperations CASCADE CONSTRAINTS;
DROP TABLE ClientOrder CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;
DROP TABLE Delivery CASCADE CONSTRAINTS;
DROP TABLE Location CASCADE CONSTRAINTS;
DROP TABLE Machine CASCADE CONSTRAINTS;
DROP TABLE Operation CASCADE CONSTRAINTS;
DROP TABLE Operation_WorkstationType CASCADE CONSTRAINTS;
DROP TABLE Operator CASCADE CONSTRAINTS;
DROP TABLE Product CASCADE CONSTRAINTS;
DROP TABLE Product_BillOfMaterials CASCADE CONSTRAINTS;
DROP TABLE ProductFamily CASCADE CONSTRAINTS;
DROP TABLE ProductionOrder CASCADE CONSTRAINTS;
DROP TABLE ProductVariant CASCADE CONSTRAINTS;
DROP TABLE Robot CASCADE CONSTRAINTS;
DROP TABLE Unit CASCADE CONSTRAINTS;
DROP TABLE Variant CASCADE CONSTRAINTS;
DROP TABLE Workstation CASCADE CONSTRAINTS;
DROP TABLE WorkstationType CASCADE CONSTRAINTS;
CREATE TABLE AutomaticMachine (ID number GENERATED AS IDENTITY, Workstation_ID varchar2(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE BillOfMaterials (parent_code varchar2(255) NOT NULL, child_code varchar2(255) NOT NULL, description varchar2(255) NOT NULL, quantity number(10) NOT NULL, PRIMARY KEY (parent_code, child_code));
CREATE TABLE BillOfOperations (sequenceNumber number(10) NOT NULL, ProductFamilyID number(10) NOT NULL, OperationID number(10) NOT NULL, PRIMARY KEY (sequenceNumber, ProductFamilyID, OperationID));
CREATE TABLE ClientOrder (ID number(10) NOT NULL, Customer_nif number(10) NOT NULL, dateOrder date NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Customer (nif number(10) NOT NULL, Location_address varchar2(255) NOT NULL, Location_zip varchar2(255) NOT NULL, name varchar2(255) NOT NULL, vatin varchar2(255) NOT NULL, email varchar2(255) NOT NULL, phoneNumber number(19) NOT NULL, category varchar2(255), PRIMARY KEY (nif));
CREATE TABLE Delivery (OrderID number(10) NOT NULL, dateDelivery date NOT NULL, Customer_nif number(10) NOT NULL, PRIMARY KEY (OrderID));
CREATE TABLE Location (address varchar2(255) NOT NULL, zip varchar2(255) NOT NULL, town varchar2(255) NOT NULL, country varchar2(255) NOT NULL, PRIMARY KEY (address, zip));
CREATE TABLE Machine (ID number GENERATED AS IDENTITY, OperatorID number NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Operation (ID number(10) NOT NULL, description varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (ID));
CREATE TABLE Operation_WorkstationType (Operation_ID number(10) NOT NULL, WorkstationType_ID varchar2(255) NOT NULL, PRIMARY KEY (Operation_ID, WorkstationType_ID));
CREATE TABLE Operator (ID number GENERATED AS IDENTITY, Workstation_ID varchar2(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Product (code varchar2(255) NOT NULL, ProductFamily_ID number(10) NOT NULL, name varchar2(255) NOT NULL UNIQUE, description varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (code));
CREATE TABLE Product_BillOfMaterials (Productcode varchar2(255) NOT NULL, BillOfMaterialsparent_code varchar2(255) NOT NULL, BillOfMaterialschild_code varchar2(255) NOT NULL, PRIMARY KEY (Productcode, BillOfMaterialsparent_code, BillOfMaterialschild_code));
CREATE TABLE ProductFamily (ID number(10) NOT NULL, name varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (ID));
CREATE TABLE ProductionOrder (OrderID number(10) NOT NULL, Productcode varchar2(255) NOT NULL, quantity number(10) NOT NULL, PRIMARY KEY (OrderID, Productcode));
CREATE TABLE ProductVariant (Product_code varchar2(255) NOT NULL, Variant_type number(10) NOT NULL, Unit_name number(10), value number(10) NOT NULL, PRIMARY KEY (Product_code, Variant_type));
CREATE TABLE Robot (ID number GENERATED AS IDENTITY, Workstation_ID varchar2(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Unit (name number(10) GENERATED AS IDENTITY, PRIMARY KEY (name));
CREATE TABLE Variant (type number(10) GENERATED AS IDENTITY, PRIMARY KEY (type));
CREATE TABLE Workstation (ID varchar2(255) NOT NULL, WorkstationType_ID varchar2(255) NOT NULL, name varchar2(255) NOT NULL UNIQUE, description varchar2(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE WorkstationType (ID varchar2(255) NOT NULL, name varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (ID));
ALTER TABLE Operator ADD CONSTRAINT FKOperator449705 FOREIGN KEY (Workstation_ID) REFERENCES Workstation (ID);
ALTER TABLE Robot ADD CONSTRAINT FKRobot492914 FOREIGN KEY (Workstation_ID) REFERENCES Workstation (ID);
ALTER TABLE AutomaticMachine ADD CONSTRAINT FKAutomaticM191868 FOREIGN KEY (Workstation_ID) REFERENCES Workstation (ID);
ALTER TABLE Machine ADD CONSTRAINT FKMachine79694 FOREIGN KEY (OperatorID) REFERENCES Operator (ID);
ALTER TABLE ClientOrder ADD CONSTRAINT FKClientOrde702977 FOREIGN KEY (Customer_nif) REFERENCES Customer (nif);
ALTER TABLE Delivery ADD CONSTRAINT FKDelivery971874 FOREIGN KEY (OrderID) REFERENCES ClientOrder (ID);
ALTER TABLE Customer ADD CONSTRAINT FKCustomer195476 FOREIGN KEY (Location_address, Location_zip) REFERENCES Location (address, zip);
ALTER TABLE Workstation ADD CONSTRAINT FKWorkstatio23355 FOREIGN KEY (WorkstationType_ID) REFERENCES WorkstationType (ID);
ALTER TABLE Operation_WorkstationType ADD CONSTRAINT FKOperation_103627 FOREIGN KEY (Operation_ID) REFERENCES Operation (ID);
ALTER TABLE Operation_WorkstationType ADD CONSTRAINT FKOperation_477889 FOREIGN KEY (WorkstationType_ID) REFERENCES WorkstationType (ID);
ALTER TABLE Product ADD CONSTRAINT FKProduct643872 FOREIGN KEY (ProductFamily_ID) REFERENCES ProductFamily (ID);
ALTER TABLE ProductVariant ADD CONSTRAINT FKProductVar601588 FOREIGN KEY (Product_code) REFERENCES Product (code);
ALTER TABLE ProductVariant ADD CONSTRAINT FKProductVar918163 FOREIGN KEY (Variant_type) REFERENCES Variant (type);
ALTER TABLE ProductVariant ADD CONSTRAINT FKProductVar493609 FOREIGN KEY (Unit_name) REFERENCES Unit (name);
ALTER TABLE ProductionOrder ADD CONSTRAINT FKProduction143899 FOREIGN KEY (OrderID) REFERENCES ClientOrder (ID);
ALTER TABLE ProductionOrder ADD CONSTRAINT FKProduction869898 FOREIGN KEY (Productcode) REFERENCES Product (code);
ALTER TABLE BillOfOperations ADD CONSTRAINT FKBillOfOper603675 FOREIGN KEY (ProductFamilyID) REFERENCES ProductFamily (ID);
ALTER TABLE BillOfOperations ADD CONSTRAINT FKBillOfOper239527 FOREIGN KEY (OperationID) REFERENCES Operation (ID);
ALTER TABLE Delivery ADD CONSTRAINT FKDelivery933023 FOREIGN KEY (Customer_nif) REFERENCES Customer (nif);
ALTER TABLE Product_BillOfMaterials ADD CONSTRAINT FKProduct_Bi931271 FOREIGN KEY (Productcode) REFERENCES Product (code);
ALTER TABLE Product_BillOfMaterials ADD CONSTRAINT FKProduct_Bi912914 FOREIGN KEY (BillOfMaterialsparent_code, BillOfMaterialschild_code) REFERENCES BillOfMaterials (parent_code, child_code);
